"""Shared data contracts used across the AquaBlend MILP pipeline."""

from .scenario_data import (
    DemandZoneInput,
    PlantInput,
    PlantZoneLinkInput,
    ScenarioData,
    SourceInput,
    SourcePlantLinkInput,
)
from .solved_data import (
    CostBreakdown,
    CostSummary,
    DataSource,
    DemandZoneResult,
    FlowResult,
    InflowQualityPlantResult,
    InputScenario,
    InputValidationPolicy,
    LoaderValidation,
    OutputValidation,
    PlantResult,
    PlantZoneFlowResult,
    PreprocessingValidation,
    QualityParameterResult,
    QualityResult,
    SolutionValidation,
    SolvedScenario,
    SolverSummary,
    SourceDecisionEvidence,
    SourcePlantFlowResult,
    SourceResult,
    ValidationCheck,
)

__all__ = [
    "CostBreakdown",
    "CostSummary",
    "DataSource",
    "DemandZoneInput",
    "DemandZoneResult",
    "FlowResult",
    "InflowQualityPlantResult",
    "InputScenario",
    "InputValidationPolicy",
    "LoaderValidation",
    "OutputValidation",
    "PlantInput",
    "PlantResult",
    "PlantZoneFlowResult",
    "PlantZoneLinkInput",
    "PreprocessingValidation",
    "QualityParameterResult",
    "QualityResult",
    "ScenarioData",
    "SolutionValidation",
    "SolvedScenario",
    "SolverSummary",
    "SourceDecisionEvidence",
    "SourceInput",
    "SourcePlantFlowResult",
    "SourcePlantLinkInput",
    "SourceResult",
    "ValidationCheck",
]